const ROLES = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  PRODUCTION_MANAGER: 'production_manager',
  SUPERVISOR: 'supervisor', 
  ACCOUNTANT: 'accountant',
  VIEWER: 'viewer',
};

// Granular permissions
const PERMISSIONS = {
  // Inventory
  INVENTORY_READ:    'inventory:read',
  INVENTORY_WRITE:   'inventory:write',
  INVENTORY_DELETE:  'inventory:delete',

  // Customers
  CUSTOMERS_READ:    'customers:read',
  CUSTOMERS_WRITE:   'customers:write',
  CUSTOMERS_DELETE:  'customers:delete',

  // Expenses
  EXPENSES_READ:     'expenses:read',
  EXPENSES_WRITE:    'expenses:write',
  EXPENSES_DELETE:   'expenses:delete',
  EXPENSES_APPROVE:  'expenses:approve',

  // Transactions / Sales
  TRANSACTIONS_READ:   'transactions:read',
  TRANSACTIONS_WRITE:  'transactions:write',
  TRANSACTIONS_DELETE: 'transactions:delete',

  // Reports
  REPORTS_READ:      'reports:read',
  REPORTS_EXPORT:    'reports:export',

  // Prices
  PRICES_READ:       'prices:read',
  PRICES_WRITE:      'prices:write',

  // Users
  USERS_READ:        'users:read',
  USERS_WRITE:       'users:write',

  // Excel
  EXCEL_IMPORT:      'excel:import',
  EXCEL_EXPORT:      'excel:export',

  // Audit Logs
  AUDIT_READ:        'audit:read',
};

// Default permission sets per role
const ROLE_DEFAULT_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS), // All permissions
  [ROLES.MANAGER]: [
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.CUSTOMERS_READ, PERMISSIONS.CUSTOMERS_WRITE,
    PERMISSIONS.EXPENSES_READ, PERMISSIONS.EXPENSES_WRITE, PERMISSIONS.EXPENSES_APPROVE,
    PERMISSIONS.TRANSACTIONS_READ, PERMISSIONS.TRANSACTIONS_WRITE,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.PRICES_READ, PERMISSIONS.PRICES_WRITE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.EXCEL_IMPORT, PERMISSIONS.EXCEL_EXPORT,
  ],
  [ROLES.PRODUCTION_MANAGER]: [
    PERMISSIONS.INVENTORY_READ, PERMISSIONS.INVENTORY_WRITE,
    PERMISSIONS.EXPENSES_READ,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.PRICES_READ,
    PERMISSIONS.EXCEL_EXPORT,
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.EXPENSES_READ, PERMISSIONS.EXPENSES_WRITE, PERMISSIONS.EXPENSES_APPROVE,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.PRICES_READ, PERMISSIONS.PRICES_WRITE,
    PERMISSIONS.EXCEL_IMPORT, PERMISSIONS.EXCEL_EXPORT,
  ],
  [ROLES.SUPERVISOR]: [
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.CUSTOMERS_READ,
    PERMISSIONS.TRANSACTIONS_READ,
    PERMISSIONS.PRICES_READ,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.REPORTS_READ,
  ],
};

module.exports = { ROLES, PERMISSIONS, ROLE_DEFAULT_PERMISSIONS };
